### ISSUE TITLE
desec & gcore providers

### ISSUE THREAD

**Issue by WladyX** [pier-oliviert/phonebook#12]
The domain i'm using is hosted on desec and gcore.
Is it possible to implement these providers?
Thank you for sharing this operator!

**Comment by ainsey11** [comment]
I've not done too much digging, but does appear that both providers have golang libraries, which providing they're not too bad to work with, should make adding these two providers fairly straight forward

https://github.com/nrdcg/desec
https://github.com/G-Core/gcore-dns-sdk-go

I'll see what I can do, currently I'm trying to finish off the RFC2136 provider which is proving a bit challenging

**Comment by WladyX** [comment]
Thank you @ainsey11 !

**Comment by ainsey11** [comment]
@WladyX just to let you know that we've pretty much wrapped up development on the desec provider in the above PR (#14)

Once all merged, I'll start working on the gcore one and with the wind behind me it should be in our next release :)

**Comment by WladyX** [comment]
wow, did not expect that to move so fast to be honest!
I saw you now support multiple providers so after gcore is done I will start using phonebook and provide feedback.
thank you!!

**Comment by ainsey11** [comment]
go for it @pier-oliviert! I've not started yet so you are more than welcome to :)

**Comment by WladyX** [comment]
@pier-oliviert can you please do a release with Gcore? looking forward to play with desec and gcore.
Thank you!

**Comment by pier-oliviert** [comment]
@WladyX I just cut the release, it should be out in a few minutes. `v0.3.7`

Let me know how it goes!

**Comment by WladyX** [comment]
i don't see it yet:
```
❯ curl https://pier-oliviert.github.io/phonebook/index.yaml
apiVersion: v1
entries:
  phonebook:
  - apiVersion: v2
    appVersion: 0.3.6
    created: "2024-10-21T12:48:58.744095443Z"
    description: Manages DNS Record within Kubernetes
    digest: ae79b3711f79c56a9735d1212cc825baeaf98531faa184f9433e5dd136f04ba2
    name: phonebook
    type: application
    urls:
    - https://github.com/pier-oliviert/phonebook/releases/download/phonebook-0.3.6/phonebook-0.3.6.tgz
    version: 0.3.6
```
❯ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "upterm" chart repository
...Successfully got an update from the "phonebook" chart repository
...Successfully got an update from the "aqua" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
❯ helm search repo phonebook
NAME               	CHART VERSION	APP VERSION	DESCRIPTION
phonebook/phonebook	0.3.6        	0.3.6      	Manages DNS Record within Kubernetes
```

```
