### ISSUE TITLE
gcore provider not working

### ISSUE THREAD

**Issue by WladyX** [pier-oliviert/phonebook#19]
```
apiVersion: se.quencer.io/v1alpha1
kind: DNSIntegration
metadata:
  labels:
    argocd.argoproj.io/instance: k8s-blue-cc-phonebook
  name: gcore
spec:
  provider:
    name: gcore
  secretRef:
    keys:
      - key: GCORE_PERMANENT_API_TOKEN
        name: GCORE_API_TOKEN
    name: phonebook-secrets
  zones:
    - myzone.com
```

```
Name:         gcore
Namespace:
Labels:       argocd.argoproj.io/instance=k8s-blue-cc-phonebook
Annotations:  <none>
API Version:  se.quencer.io/v1alpha1
Kind:         DNSIntegration
Metadata:
  Creation Timestamp:  2024-11-01T20:06:44Z
  Finalizers:
    phonebook.se.quencer.io/deployment
  Generation:        1
  Resource Version:  90979843
  UID:               b0c39020-951e-448c-8bbd-df03550567e0
Spec:
  Provider:
    Name:  gcore
  Secret Ref:
    Keys:
      Key:   GCORE_PERMANENT_API_TOKEN
      Name:  GCORE_API_TOKEN
    Name:    phonebook-secrets
  Zones:
    myzone.com
Status:
  Conditions:
    Last Transition Time:  2024-11-01T20:06:44Z
    Reason:                Deployment.apps "provider-gcore" is invalid: spec.template.spec.containers[0].image: Required value
    Status:                Error
    Type:                  Deployment
Events:                    <none>
```

**Comment by pier-oliviert** [comment]
Sorry about that, the release process is very manual and error prone. I have rebuilt and reshipped 0.3.7. Usually, helm chart versions needs to increment but I didn't do it.

Can you try again? You might need to remove phonebook from your helm repo or at the very least force an update.

**Comment by WladyX** [comment]
No worries, but i tried everything that I could think off, I am deploying with argo, I've tried hard refresh, removing the app, etc, nothing worked, same error, I suspect this is still present.
Can you please reopen it and maybe bump the chart version so we can exclude the caching of the old version?
Thank you!

**Comment by pier-oliviert** [comment]
@WladyX Before I make changes to the helm chart can you test this `DNSIntegration` for me first?

```yaml
apiVersion: se.quencer.io/v1alpha1
kind: DNSIntegration
metadata:
  labels:
    argocd.argoproj.io/instance: k8s-blue-cc-phonebook
  name: gcore
spec:
  provider:
    name: gcore
    image: "ghcr.io/pier-oliviert/providers-gcore:v0.3.7"
  secretRef:
    keys:
      - key: GCORE_PERMANENT_API_TOKEN
        name: GCORE_API_TOKEN
    name: phonebook-secrets
  zones:
    - myzone.com
```

You can specify images directly and I want to make sure the image loads OK for you. One thing I realized is that all images are built for x64 platform so I want to make sure the image is actually running in your cluster.
