### ISSUE TITLE
desec provider not working

### ISSUE THREAD

**Issue by WladyX** [pier-oliviert/phonebook#20]
```
apiVersion: se.quencer.io/v1alpha1
kind: DNSRecord
metadata:
  labels:
    argocd.argoproj.io/instance: k8s-blue-cc-phonebook
  name: test-pb
  namespace: phonebook
spec:
  name: test-pb
  recordType: A
  targets:
    - 127.0.0.1
  ttl: 60
  zone: myzone.com
```
```
Name:         test-pb
Namespace:    phonebook
Labels:       argocd.argoproj.io/instance=k8s-blue-cc-phonebook
Annotations:  <none>
API Version:  se.quencer.io/v1alpha1
Kind:         DNSRecord
Metadata:
  Creation Timestamp:  2024-11-01T19:56:27Z
  Finalizers:
    phonebook.se.quencer.io/finalizer
  Generation:        1
  Resource Version:  90971193
  UID:               cda84e9e-e28b-45d9-9e87-178c35ec5e81
Spec:
  Name:         test-pb
  Record Type:  A
  Targets:
    127.0.0.1
  Ttl:   60
  Zone:  myzone.com
Status:
  Conditions:
    Last Transition Time:  2024-11-01T19:56:27Z
    Reason:                Integration found: desec
    Status:                Completed
    Type:                  Integration
    Last Transition Time:  2024-11-01T19:56:27Z
    Reason:                PB-DESEC-#0002: Unable to create record -- 405: body: {"detail":"Method \"POST\" not allowed."}
    Status:                Error
    Type:                  Provider
Events:                    <none>
```
```
apiVersion: se.quencer.io/v1alpha1
kind: DNSIntegration
metadata:
  labels:
    argocd.argoproj.io/instance: k8s-blue-cc-phonebook
  name: desec
spec:
  provider:
    name: desec
  secretRef:
    keys:
      - key: DESEC_TOKEN
        name: DESEC_TOKEN
    name: phonebook-secrets
  zones:
    - myzone.com
```
