### ISSUE TITLE
Add Comment and Tags for Cloudflare DNS record

### ISSUE THREAD

**Issue by c-nugraha** [pier-oliviert/phonebook#25]
Hi there, i'm trying out phonebook for managing Cloudflare DNS record and it works great! 
I have a feature request for the Cloudflare provider.

Currently there is no indication that a DNS record was managed by phonebook. Cloudflare DNS record does have a [Record Attributes](https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/) to give information about the record. I think it would be great to be able to add Comment or Tags directly from phonebook.

Maybe the CRD looks like this 
```
apiVersion: se.quencer.io/v1alpha1
kind: DNSRecord
metadata:
  name: dnsrecord-sample
  namespace: phonebook-system
spec:
  zone: mydomain.com
  recordType: A
  name: helloworld
  targets:
    - 127.0.0.1
  comment: "managed by phonebook"
  tags:
    - key1:value1
    - key2:value2
``` 

Thanks!
