### ISSUE TITLE
dnsrecords not working

### ISSUE THREAD

**Issue by WladyX** [pier-oliviert/phonebook#26]
```
phonebook-controller-586dcd6644-rc46g controller 2024-11-17T09:55:04+02:00	INFO	Finalizer didn't exists	{"controller": "dnsrecord", "controllerGroup": "se.quencer.io", "controllerKind": "DNSRecord", "DNSRecord": {"name":"test-pb","namespace":"phonebook"}, "namespace": "phonebook", "name": "test-pb", "reconcileID": "7a58290f-98b8-4f39-bcfd-bf8406e48ebb"}
```

```
kd dnsrecords.se.quencer.io test-pb
Name:         test-pb
Namespace:    phonebook
Labels:       argocd.argoproj.io/instance=k8s-blue-cc-phonebook
Annotations:  <none>
API Version:  se.quencer.io/v1alpha1
Kind:         DNSRecord
Metadata:
  Creation Timestamp:  2024-11-17T07:55:04Z
  Finalizers:
    phonebook.se.quencer.io/finalizer
  Generation:        1
  Resource Version:  108362526
  UID:               5cf6582b-72ce-49bb-8c4a-934e9161e6b2
Spec:
  Integration:  gcore
  Name:         test-pb
  Record Type:  A
  Targets:
    127.0.0.4
  Ttl:   121
  Zone:  zone.com
Status:
  Conditions:
    Last Transition Time:  2024-11-17T07:55:04Z
    Reason:                Resource locked
    Status:                Locked
    Type:                  Integration
Events:                    <none>
```

```
---
apiVersion: se.quencer.io/v1alpha1
kind: DNSRecord
metadata:
  name: test-pb
spec:
  zone: zone.com
  recordType: A
  name: test-pb
  ttl: 121
  targets:
    - 127.0.0.4
  # integration: desec
  integration: gcore

```

I am using the latest phonebook version 0.3.8, I have removed the DNS record from gcore, removed the manifest form k8s, reapplyed the manifest

**Comment by pier-oliviert** [comment]
Hmm, I think something's wrong with the release. The image tags didn't carry over, for some reason.

```
apiVersion: se.quencer.io/v1alpha1
kind: DNSIntegration
metadata:
  name: gcore
spec:
  provider:
    name: desec
    image: ghcr.io/pier-oliviert/providers-gcore:v0.3.8
  zones:
    - whatever.com
  secretRef:
    name: desec
    keys:
      - key: token
        name: GCORE_API_TOKEN
```


The error message and the resource locks isn't great, I'll need to fix this for 0.3.9
